### ISSUE TITLE
Loading array class with ClassLoader.loadClass(String) doesn't work

### ISSUE THREAD

**Issue by whiskeysierra** [jhalterman/typetools#27]
I have a lambda that looks like this:

```java
(String[] strings) -> strings.toString();
```

If I try to resolve the raw arguments it gives me `Unknown.class`. So I stepped through the code with a debugger and finally arrived at [TypeDescriptor:351](https://github.com/jhalterman/typetools/blob/master/src/main/java/net/jodah/typetools/TypeDescriptor.java#L351)

```java
return loader == null ? Class.forName(sb.toString()) : loader.loadClass(sb.toString());
```

Evaluating the expression yields `Method threw 'java.lang.ClassNotFoundException' exception.`.
If I manually set `loader = null` with the debugger it works.

**Comment by jhalterman** [comment]
This JDK bug indicates we'll need a workaround:

http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6434149

Thanks for filing.

**Comment by jhalterman** [comment]
0.4.7, which includes this fix, is released.
