### ISSUE TITLE
Contribution back to Spring Framework

### ISSUE THREAD

**Issue by artembilan** [jhalterman/typetools#4]
Hi, @jhalterman !

Your work looks good and I have to admit that it resolve my `additional type parameter` issue. At least at a glance with smoky test.

I see you mention in your `TypeResolver` the `org.springframework.core.GenericTypeResolver`.
So, how about to contribute it back to Spring? 

We have there several issues with generics on Lambdas as well. 

Anyway we will consider to use your work somehow to make our `GenericTypeResolver` more stable.

Thank you very much!

**Comment by jhalterman** [comment]
Closing for now.
