### ISSUE TITLE
Raw Arguments of a casted method reference are not determined correctly

### ISSUE THREAD

**Issue by Vampire** [jhalterman/typetools#42]
Executing the code

```java
public class Test {
    public static void main(String[] args) {
        System.out.println(TypeResolver.resolveRawArgument(IListener.class, ((IListener<MessageReceivedEvent>) mre -> handle(mre)).getClass()));
        System.out.println(TypeResolver.resolveRawArgument(IListener.class, ((IListener<MessageReceivedEvent>) Test::handle).getClass()));
    }
    private static void handle(MessageEvent me) {}
    private interface Event {}
    private interface MessageEvent extends Event {}
    private interface MessageReceivedEvent extends MessageEvent {}
    private interface IListener<T extends Event> { void handle(T event); }
}
```

results in the output

```
interface Test$MessageReceivedEvent
interface Test$MessageEvent
```

I'd expect both lines to be `interface Test$MessageReceivedEvent`.
This seems to be a missing special handling for method references.

**Comment by csoroiu** [comment]
I the code behaves as designed. And I'll explain below what happens.

Basically at compile time the lambda expression `mre -> handle(mre)` gets translated into a synthetic method and a reference to that method (`invokedynamic` for that reference).

The synthetic method is generate inside the `Test` class and has the signature/name:
`private static void lambda$main$0(MessageReceivedEvent event)`.

The `TypeResolver.resolveRawArgument` resolves the argument to `MessageReceivedEvent` in this first case, while in the second case we already pass a reference to `handle` method which gets resolved to `MessageEvent`. 

This is fine and respects the Liskov substitution principle, basically the `handle` method is more general and accepts any subtype of `MessageEvent` as argument.

While I agree that this might not be inline with the actual source code, it is the best the library can do.
The anonymous class generated by the `invokeDynamic` instruction does not save the type parameters, thus, in the case of lambda's and method references, the type resolver code falls back to detecting the parameters of the referred method.

**Comment by Vampire** [comment]
Hm, ok, thx for the info. While I thought about it more after reporting here I feared it would be like that. :-(
