### ISSUE TITLE
resolveRawArguments not working with method references

### ISSUE THREAD

**Issue by pderop** [jhalterman/typetools#5]
Hi,

I'm not sure if this is bug or if I'm just facing the case of "Unresolvable Lambda Type Arguments" mentioned in the documentation, but I'm not able to get lambda argument types when I'm using Class :: instanceMethod method references:

What I'm trying to do is the following: I have the following sample codes:

    interface Service {
    }

    static class ServiceImpl implements Service {
    }

    static class Client {
        void bind(Service impl) {
        }
    }

    BiConsumer<Client, Service> bc = Client::bind;

And I would like to get the type of the first and second BiConsumer type arguments.

But the following:

    BiConsumer<Client, Service> bc = Client::bind;
    Class<?>[] types = TypeResolver.resolveRawArguments(BiConsumer.class, bc.getClass());
    System.out.println(Arrays.toString(types));        

displays this (not ok):

    interface org.apache.felix.dm.builder.java8.impl.Test$Service, 
    class     net.jodah.typetools.TypeResolver$Unknown

However, the following:

    BiConsumer<Client, Service> bc = (c, s) -> c.bind(s);
    Class<?>[] types = TypeResolver.resolveRawArguments(BiConsumer.class, bc.getClass());
    System.out.println(Arrays.toString(types));        

seems to work:

     class org.apache.felix.dm.builder.java8.impl.Test$Client, 
     interface org.apache.felix.dm.builder.java8.impl.Test$Service]

So, am I just facing a case that is not resolvable (like the "Unresolvable Lambda Type Arguments" section is mentioning in the documentation) ? or is there a bug ?

as far as I understand, "(c, s) -> c.bind(s)" is similar to Client::bind,
am I correct ?

many thanks.
/Pierre

**Comment by jhalterman** [comment]
Hi Pierre - They are similar, but the bytecode is a bit different and instance method references are something I just hadn't added support for yet. Thanks for bringing this up though - looking into it now...

**Comment by jhalterman** [comment]
@pderop This should be resolved now. Let me know if it looks good and I'll cut a new release.

Curious - is this being considered for inclusion in Felix?

**Comment by pderop** [comment]
Hi Jonathan;

You made my day, excellent, it works fine in my environment ! So, how do you know it would be for Felix (DependencyManager) ? 

:-)

So, I'm working on a new java8 builder prototype that leverages the existing Apache Felix Dependency Manager API using type-safe java8 constructs (essentially method references); but nothing is yet committed. I hope to commit soon this new library in my sandbox (that will probably use your (lightweight, but useful) typetool. I will then open a Felix Jira issue and will discuss with other DM contributors to see what they think about, before going ahead.

By the way:

- when do you plan to make a release ?
- And also, it would be great if you could OSGi-ify typetools (using maven-bnd-plugin, since your are using maven) ? If you are interested, I can create a new issue and provide a fix for this in your pom ? just tell me.

cheers;
/Pierre

**Comment by jhalterman** [comment]
@pderop I guessed you were working on felix from your package names. I can cut a release whenever you'd like, but if you want to submit a pull request for OSGI support that would be great. I can cut a release right after that merges.

**Comment by pderop** [comment]
I just made a pull request (hope I did it well, first time I'm doing this).
I modified the pom.xml and also proposed a patch because it was actually not working within Felix (but only working outside OSGi). See my comments in the pull request.

thanks.
