### ISSUE TITLE
How to create instance with private constructor?

### ISSUE THREAD

**Issue by scruel** [jhalterman/typetools#75]
Notice the README [common-use-cases section](https://github.com/jhalterman/typetools#common-use-cases)

should `private GenericDAO()`  be `public GenericDAO()` ?

Same, `persistentClass` should be public, then make outer instance can access it.

**Comment by jhalterman** [comment]
It's just an example, but yea, the constructor should probably be protected or public (want to send a PR?). `persistentClass` and `idClass` are meant to be visible just to the child classes, although again, it's just an example.

**Comment by scruel** [comment]
> 
> 
> It's just an example, but yea, the constructor should probably be protected or public (want to send a PR?). `persistentClass` and `idClass` are meant to be visible just to the child classes, although again, it's just an example.

Got it, I may send a PR, THX~

**Comment by scruel** [comment]
Code can run in tests.
