### ISSUE TITLE
How does typetools work for nested generics?

### ISSUE THREAD

**Issue by vivin** [jhalterman/typetools#8]
I just ran into this tool today and it looks pretty awesome! I had a question about how typetool handles nested generics. Adapting the example from your readme, suppose I had:

``` java
interface Foo<T1, T2> {}
class Bar implements Foo<List<Integer>, List<String>> {}

Class<?>[] typeArgs = TypeResolver.resolveRawArguments(Foo.class, Bar.class);
```

What would `typeArgs` contain? I'm assuming that it would just contain `List.class`, correct? All `List<T>` instances will share the same `List.class` instance regardless of the type of `T` due to type-erasure, and there is no way to represent the "class" of a set of strings vs. a set of integers (because that distinction is meaningless). IMO it might be due to the conflation of class-instances with runtime type-tokens. It works in cases where the class instance has a one-to-one mapping (semantically) with the type, but this mapping breaks down when you have a generic class that can work with objects of any type. There is no facility (that I know of) to represent the type of an instance of that generic class that _also_ includes information about its generic parameter(s). Considering that class instances represent... well, class instances, it makes sense to say that the class of `List<String>` and `List<Integer>` is just `List.class` because the `List<T>` class itself doesn't work on any specific type of object. 

Is there a workaround for this scenario?

**Comment by jhalterman** [comment]
You're right that - right now resolveRawArguments just returns raw `List.class`. I specifically called that method `resolveRawArguments` because I wanted to leave room for resolving parameterized arguments, which could return an array/list of [TypeToken](https://code.google.com/p/guava-libraries/wiki/ReflectionExplained)-like things from which you could learn the raw type, if you wish, or the parameterized arguments. Mostly people are interested in learning raw arguments that aren't nested which is why I haven't bothered doing parameterized stuff yet :)

**Comment by jhalterman** [comment]
BTW - If you have any suggestions for what this feature could look like, feel free to throw them out.

In the meantime, you might look at Tatu's [Classmate](https://github.com/FasterXML/java-classmate) library, which is similar to TypeTools and I believe can resolve parameterized type information, in addition to raw types.

**Comment by vivin** [comment]
Awesome! Thanks a bunch for the quick response! I just ran into super-type tokens which maintain generic information via anonymous classes. The approach looks very appealing, but is kind of fragile because if you forget the trailing `{}` when you create an anonymous class-instance, the code doesn't work. Perhaps if there was a way to abstract that in some way, the super-type token approach would be perfect.

I'll see if I can come up with some possible feature suggestions. Thanks again! :)

**Comment by lorenzleutgeb** [comment]
Any chance that resolution of parameterized types might still make it into `typetools`? I implemented this in another library by first constructing a `Map<Type, Type>` and then walking `ParameterizedTypes` of arbitrary depth by substituting with the information in the map. I think that #12 would go in a similar direction.

**Comment by jhalterman** [comment]
I'd like to, but at this point I'd say it would have to be a contribution from someone.

**Comment by gselzer** [comment]
Sorry to discuss on a closed topic, but was the nested generics work applied to lambda parameterized types?  Using `reify(Function.class, <thing_to_reify>.class)`, `typetools` seems to adequately reify my 
`class Foo implements Function<List<Double>, List<String>>` 
however struggles greatly in reifying my 
`Function<List<Double>, List<String> fooFunction = (list) -> {...};`.
`typetools` can obviously return the raw arguments of a lambda, however that does not help with nested generics. Is there another method I am not seeing/understanding? Are we even able to access nested generics information using the `ConstantPool`?
