### ISSUE TITLE
Not working for parameterized class implemented a functional interface

### ISSUE THREAD

**Issue by Robocop83** [jhalterman/typetools#9]
I wrote this simple setter class using lambda

public class Setter<PARAMETER> implements Consumer<PARAMETER>
{
	private Consumer<PARAMETER> consumer;

	public Setter(Consumer<PARAMETER> consumer)
	{
		this.consumer = consumer;
	}

	@Override
	public void accept(PARAMETER parameter)
	{
		consumer.accept(parameter);
	}
}

then I created a JunitTest

	public void testLambdaSetter()
	{
		StringBuffer stringBuffer = new StringBuffer();
		Setter<String> setter = new Setter<String>(stringBuffer::append);
		
		Class<?>[] classes = TypeResolver.resolveRawArguments(Consumer.class, setter.getClass());
		assertEquals(String.class, classes[0]);
	}

and it fails

**Comment by jhalterman** [comment]
I can't tell from your example - where is PARAMETER defined?

**Comment by jhalterman** [comment]
So this scenario is actually not resolvable via TypeTools or any other mechanism. Set aside the method reference, and basically we have:

```
Setter<String> setter = new Setter<String>();
```

The type argument `String` needs to be captured in a type definition in order for it to be resolvable. Ex:

```
StringSetter extends Setter<String> {...
```

When it comes to resolving type arguments from lambdas, the lambda has to be a functional interface. Ex:

```
    Consumer<String> consumer = c -> {};
    Class<?> type = TypeResolver.resolveRawArgument(Consumer.class, consumer.getClass());
    assertEquals(type, String.class);
```

**Comment by Robocop83** [comment]
Ok I solved used this syntax:

Setter<String> setter = new Setter<String>() {};

Thanks
